- btrdb/__init__.py
- btrdb/utils/ray.py
This PR adds a new `shareable` flag to the `connect()` method. Connections created in this way can be serialized and shared among Ray workers in a Ray cluster. However, this is potentially insecure: it is *possible* (POC in development) to pull an API key out of the serialized object as it rests in the Plasma store. However, this requires access to the same Ray cluster.
Uses the `semver` package to choose the right Ray serialization method based on which version of Ray is installed.
Usage looks as follows:
```python
import ray
import btrdb
ray.init(ignore_reinit_error=True)
conn  =  btrdb.connect(profile='collab', shareable=True)
conn_copy = ray.get(ray.put(conn))  #ok
```
```python
import ray
import btrdb
ray.init(ignore_reinit_error=True)
conn  =  btrdb.connect(profile='collab', …
```
> Make BTrDB connections serializable in Ray

- btrdb/utils/ray.py
I noticed that our builds were failing because I did not have `ray` or `semver` installed and they were added to `btrdb/utils/ray.py` with Gabe's serialization work. I was hesitant to add them as requirements because they are only really necessary when the user is trying to use ray with the bindings, so I added a try/except to throw an exception when a user tries to register a custom serializer but does not have these modules installed.
I'm open to feedback on this, this is just the first thing that came to mind.
> make ray and semver dependencies optional

- release.sh
I found the solution here: https://mkyong.com/mac/sed-command-hits-undefined-label-error-on-mac-os-x/
tested it locally on my mac and in a docker container to verify that it works on both osx and linux now.
> make sed cmd in release.sh compatible with osx

- docs/source/index.rst
This PR updates the build badge at the top of the btrdb-python docs to point to our github actions build. Previously it was pointing to Travis, but we haven't used Travis in at least six months
> update build status in docs to show github actions

- setup.py
This PR changes the link to the new readthedocs page, updates to docs should now get automatically pushed there
> change link to docs in setup.py

- setup.py
This PR changes the docs path in setup.py back to the old documentation link. We decided it was best to not change it, and I was able to get access to the old readthedocs.
> change path in setup back to old docs

- btrdb/conn.py
- requirements.txt
Certifi certs are being provided as part of the software package to alleviate issues with finding root certs, out of date OS certs, etc.
> Certifi provides Mozilla's carefully curated collection of Root Certificates for validating the trustworthiness of SSL certificates while verifying the identity of TLS hosts. It has been extracted from the Requests project.
> bundles certifi certs as dependency

- btrdb/point.py
Update documentation about stat point 'time'
> fix stat pont documentation

- benchmarks/benchmark_streamset_reads.py
- btrdb/endpoint.py
- btrdb/stream.py
* The streamset was passing the incorrect params to the endpoint
* The endpoint does not return a `version` in its response, just `stat` and `arrowBytes`
Params have been updated and a NoneType is passed around to ignore the
lack of version info, which lets us use the same logic for all bytes
decoding.
Added multistream benchmark methods for multistream reads with and without timesnapping.
> Multistream read bench insert bench

- btrdb/conn.py
- btrdb/endpoint.py
- btrdb/stream.py
Previously, the debug logging in the api would create the f-strings no matter if logging.DEBUG was the current log level or not.
This can impact the performance, especially for benchmarking.
Now, a cached IS_DEBUG flag is created for the stream operations, and other locations, the logger.isEnabledFor boolean is checked.
Note that in the stream.py, this same function call is only executed once, and the results are cached for the rest of the logic.
> Optimize logging calls

- .github/workflows/release.yaml
- btrdb/conn.py
- btrdb/endpoint.py
- btrdb/exceptions.py
- btrdb/stream.py
- btrdb/transformers.py
- tests/btrdb/test_stream.py
- tests/btrdb_integration/conftest.py
- tests/btrdb_integration/test_conn.py
- tests/btrdb_integration/test_regressions.py
- tests/btrdb_integration/test_stream.py
- tests/btrdb_integration/test_streamset.py
Added in an arrow_to_dataframe test, some cleaning as well.
> Update pandas testing and fix flake8 issues

- btrdb/transformers.py
- pyproject.toml
Small regression in the arrow_to_dataframe method, trying to set the pandas index as the time column leads to pretty massive slowdowns in performance. A pandas issue, not ours. But for our use cases, we like to use pandas dataframes.
If we need to set the index, we can do that at a different point of the workflow, not when we are getting the data back from arrow. This makes the arrow method appear to be very slow when it is not.
> Converting pandas index takes very long, add in arrow_table.

- release.sh
Story Details: https://app.shortcut.com/pingthing/story/25528/update-release-sh-script-in-btrdb-python-to-edit-the-version-number-in-the-pyproject-toml
This changes the release.sh script to also update the pyproject.toml version.
> Have release script update pyproject.toml file

- btrdb/stream.py
Previously, the arrow endpoints are not guaranteed to present their data in a sorted order, this PR lets the user set that for single stream calls, and sorts by time for the streamset operations by default.
Streamset transformers like `streamset.to_dataframe` in the old version of the api used a `PointBuffer` that would sort the values by time before returning to the user.
The single stream arrow methods now have a boolean argument `sorted` to let the user specify if they want to sort the returned table on the `'time'` column or not.
This is False by default.
The streamset methods though, will be sorted by default and the user wont be able to switch that. We can change that later if needed.
> Provide option to sort the arrow tables

- btrdb/conn.py
Currently our logic chunks data to send over gRPC according to numbers of rows of data, this led to large streamsets in the multivalue api erroring out while trying to recv this data on the client side.
This PR sets the limit for the client to receive from the server to be unlimited for the time being. This will allow arbitrarily-sized streamsets to have successful multivalue queries.
In the future we should update our logic to better handle these size limits when sending from the server, but this is a patch fix for now.
I tested this for 5000 streams on ni4ai, with a `sampling_frequency` of `30` for 100seconds of data, this would error out on the master branch, but successfully returns the data on with this PR.
MWE
------
```python
import btrdb
conn = …
```
> [sc-25841] Remove 4MB limit for gRPC message payloads

- .github/workflows/release.yaml
- .readthedocs.yaml
- CHANGELOG.md
- btrdb/conn.py
- btrdb/stream.py
- btrdb/transformers.py
- btrdb/version.py
- docs/requirements.txt
- docs/source/api-index.rst
- docs/source/api/conn.rst
- docs/source/api/streams.rst
- docs/source/api/transformers.rst
- docs/source/changelog.rst
- docs/source/concepts.rst
- docs/source/conf.py
- docs/source/explained.rst
- docs/source/index.rst
- docs/source/installing.rst
- docs/source/quick-start.rst
- docs/source/working.rst
- docs/source/working/arrow-enabled-queries.rst
- docs/source/working/dash.rst
- docs/source/working/multistream.rst
- docs/source/working/server.rst
- pyproject.toml
- release.sh
master and staging branches got out of sync. This updates the staging branch to latest as well.
> Update staging branch with latest `master` changes

- btrdb/stream.py
- tests/btrdb_integration/test_streamset.py
`sampling_frequency` in python client api does not correctly sample/align data for frequencies < 1Hz
> Add integration tests to check for misbehaving sampling frequencies.

- README.md
- btrdb/conn.py
- btrdb/stream.py
- tests/btrdb/test_conn.py
- tests/btrdb/test_stream.py
- tests/btrdb/test_transformers.py
- tests/btrdb/utils/test_credentials.py
Catch master branch up to date with staging.
> Update from staging

- pyproject.toml
- setup.cfg
- setup.py
When doing `pip install --verbose` for the project, we get some deprecation warnings for the build "configuration would be ignored/result in error due to `pyproject.toml` [...] By 2023-Oct-30, you need to update your project and remove deprecated calls or your builds will no longer be supported."
To stick to the PEP standards and the setuptools, this PR attemps to fix that.
Note: we can leave an minimal setup.py if we're using project.toml, see the docs [here](https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html).
> Fix build deprecation warnings in using pyproject.toml and setuptool

- btrdb/transformers.py
- tests/btrdb/test_transformers.py
The columns arg have been noted to deprecate since v5.8. 
This PR updates both `to_dataframe` and `arrow_to_dataframe` functions as well as relevant tests. 
May not need to test that TypeError stating `columns` was given.
> Remove deprecated columns arg from to_dataframe and arrow_to_dataframe

- btrdb/stream.py
Bug fix:
```
TypeError                                 Traceback (most recent call last)
Cell In[39], line 1
----> 1 streamset.earliest()
File /opt/conda/lib/python3.10/site-packages/btrdb/stream.py:1602, in StreamSetBase.earliest(self)
1597     logger.debug(f"versions: {versions}")
1598 earliest_points_gen = self._btrdb._executor.map(
1599     lambda s: s.nearest(start, version=versions.get(s.uuid, 0), backward=False),
1600     self._streams,
1601 )
-> 1602 for point, _ in earliest_points_gen:
1603     earliest.append(point)
1605 return tuple(earliest)
TypeError: cannot unpack non-iterable NoneType object
```
and also for latest.
> bug fix earliest/latest for empty streams

- .github/workflows/release.yaml
- .pre-commit-config.yaml
- Update pre-commit plugin versions.
- turn on coverage report in gh actions checks on PRs
> Update pre-commit versions and add coverage report to gh actions

- btrdb/utils/general.py
- tests/btrdb/utils/test_general.py
Just a helper method to make pointwidth class work with the Arrow table's `time` column dtype of panda.TimeStamp when in dataframe.
> Add to_timedelta method for pointwidth class

- btrdb/exceptions.py
Previously, when we encountered an exception that was either a `BTrDBError` or a `RpcError`, we would then parse both of these exception types as a `btrdberror`, which can lead to confusing error messages when apifrontend is down.
You could get an error like the following:
```
conn.info()
>>> BtrdbError stream removed
```
When this is acually a grpc/rpc error about the connection/stream between the server/client. This can lead folks to thinking that their data `streams` have been deleted, etc.
> Update exception handling to support RpcErrors.

- btrdb/transformers.py
In this PR, improvements for:
- memory usage of converting from arrow Table to pandas [sc-25947]
- for-loops in renaming columns with name_callable (tested for 10k streams, improved from ~26sec to ~16sec 1.6x faster)
> Improve arrow_to_dataframe for large amounts of columns

- btrdb/stream.py
- tests/btrdb_integration/test_streamset.py
When the amount of streams in a streamset grows into the 100s+, the join logic for windows and aligned windows queries became a computational burden due to the join logic in pyarrow for tables only operating on a table at a time.
Since we can just join on the 'time' column,  a simpler approach is to iterate through all windowed data, get a unique sorted list of all timestamps, preallocate a null arrow table for all data with the time column being all the unique sorted timestamps above, and then take all the values that are returned from the windows queries and replace the null entries with their available data. This is needed because aligned windows queries will return an empty table for timeranges where there are no data present, while windows queries will return an entry for every …
> Test new join

- btrdb/__init__.py
- btrdb/conn.py
- btrdb/endpoint.py
- btrdb/exceptions.py
- btrdb/stream.py
- btrdb/transformers.py
- btrdb/utils/timez.py
- docs/requirements.txt
- docs/source/api/streams.rst
- docs/source/concepts.rst
- docs/source/conf.py
- docs/source/explained.rst
- docs/source/index.rst
- docs/source/installing.rst
- docs/source/quick-start.rst
- docs/source/working/arrow-enabled-queries.rst
- docs/source/working/stream-manage-metadata.rst
- docs/source/working/stream-query-manage.rst
- docs/source/working/stream-view-data.rst
- docs/source/working/streamsets.rst
- tests/btrdb/test_base.py
- tests/btrdb/test_conn.py
- tests/btrdb_integration/test_conn.py
final prep before a new release
> Initial docstrings and a new test.

- .github/workflows/release.yaml
- btrdb/version.py
- pyproject.toml
- tests/btrdb_integration/test_conn.py
- tests/btrdb_integration/test_streamset.py
Numpy 2.0 has some breaking changes we are currently using, and the tests for a bogus api key was not generic enough to support tempsgs profiles.
We also dropped the 3.7 support and made a todo to support 3.12
> Release v5.33.0

- btrdb/stream.py
- tests/btrdb/test_stream.py
Prior when updating tags if the tag field was not set (and for example collection was) we would copy the tags and send them over this was wasteful and with the new metadata schema changes created errors.
This PR alleviates that problem and updates the test to be accurate with the new approach.
> Fix Redundant Tag Sending
